version: "3.7"

services:
  item-app:
    image: gemm123/item-app:v1
    restart: always
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm start"
    ports:
      - 80:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      NODE_ENV: production 
      DB_HOST: item-db
  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dicoding
volumes:
  app-db:
